<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://services.wsserver.webservices.koinos/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://services.wsserver.webservices.koinos/" name="DocumentService">
    <import namespace="http://wsserver.webservices.koinos/" location="DocumentService.wsdl1"/>
    <wsp:Policy wsu:Id="DocumentRepositoryServicePortBinding_MTOM_Policy">
        <ns1:OptimizedMimeSerialization xmlns:ns1="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization" wsp:Optional="true"/>
    </wsp:Policy>
    <binding xmlns:ns2="http://wsserver.webservices.koinos/" name="DocumentRepositoryServicePortBinding" type="ns2:DocumentRepository">
        <wsp:PolicyReference URI="#DocumentRepositoryServicePortBinding_MTOM_Policy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="download">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="getContent">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="upload">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="DocumentService">
        <port name="DocumentRepositoryServicePort" binding="tns:DocumentRepositoryServicePortBinding">
            <soap:address location="http://localhost:8081/DocumentService"/>
        </port>
    </service>
</definitions>